// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"goinv/ent/item"
	"goinv/ent/storagelocation"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (i *ItemQuery) CollectFields(ctx context.Context, satisfies ...string) (*ItemQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return i, nil
	}
	if err := i.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return i, nil
}

func (i *ItemQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(item.Columns))
		selectedFields = []string{item.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "storageLocation":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&StorageLocationClient{config: i.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, storagelocationImplementors)...); err != nil {
				return err
			}
			i.withStorageLocation = query
		case "createdAt":
			if _, ok := fieldSeen[item.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, item.FieldCreatedAt)
				fieldSeen[item.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[item.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, item.FieldUpdatedAt)
				fieldSeen[item.FieldUpdatedAt] = struct{}{}
			}
		case "name":
			if _, ok := fieldSeen[item.FieldName]; !ok {
				selectedFields = append(selectedFields, item.FieldName)
				fieldSeen[item.FieldName] = struct{}{}
			}
		case "quantity":
			if _, ok := fieldSeen[item.FieldQuantity]; !ok {
				selectedFields = append(selectedFields, item.FieldQuantity)
				fieldSeen[item.FieldQuantity] = struct{}{}
			}
		case "category":
			if _, ok := fieldSeen[item.FieldCategory]; !ok {
				selectedFields = append(selectedFields, item.FieldCategory)
				fieldSeen[item.FieldCategory] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		i.Select(selectedFields...)
	}
	return nil
}

type itemPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []ItemPaginateOption
}

func newItemPaginateArgs(rv map[string]any) *itemPaginateArgs {
	args := &itemPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*ItemWhereInput); ok {
		args.opts = append(args.opts, WithItemFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (sl *StorageLocationQuery) CollectFields(ctx context.Context, satisfies ...string) (*StorageLocationQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return sl, nil
	}
	if err := sl.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return sl, nil
}

func (sl *StorageLocationQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(storagelocation.Columns))
		selectedFields = []string{storagelocation.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "items":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ItemClient{config: sl.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, itemImplementors)...); err != nil {
				return err
			}
			sl.WithNamedItems(alias, func(wq *ItemQuery) {
				*wq = *query
			})
		case "createdAt":
			if _, ok := fieldSeen[storagelocation.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, storagelocation.FieldCreatedAt)
				fieldSeen[storagelocation.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[storagelocation.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, storagelocation.FieldUpdatedAt)
				fieldSeen[storagelocation.FieldUpdatedAt] = struct{}{}
			}
		case "name":
			if _, ok := fieldSeen[storagelocation.FieldName]; !ok {
				selectedFields = append(selectedFields, storagelocation.FieldName)
				fieldSeen[storagelocation.FieldName] = struct{}{}
			}
		case "size":
			if _, ok := fieldSeen[storagelocation.FieldSize]; !ok {
				selectedFields = append(selectedFields, storagelocation.FieldSize)
				fieldSeen[storagelocation.FieldSize] = struct{}{}
			}
		case "color":
			if _, ok := fieldSeen[storagelocation.FieldColor]; !ok {
				selectedFields = append(selectedFields, storagelocation.FieldColor)
				fieldSeen[storagelocation.FieldColor] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		sl.Select(selectedFields...)
	}
	return nil
}

type storagelocationPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []StorageLocationPaginateOption
}

func newStorageLocationPaginateArgs(rv map[string]any) *storagelocationPaginateArgs {
	args := &storagelocationPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*StorageLocationWhereInput); ok {
		args.opts = append(args.opts, WithStorageLocationFilter(v.Filter))
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
