// Code generated by ent, DO NOT EDIT.

package ent

import (
	"goinv/ent/item"
	"goinv/ent/schema"
	"goinv/ent/storagelocation"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemMixin := schema.Item{}.Mixin()
	itemMixinFields0 := itemMixin[0].Fields()
	_ = itemMixinFields0
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescCreatedAt is the schema descriptor for created_at field.
	itemDescCreatedAt := itemMixinFields0[0].Descriptor()
	// item.DefaultCreatedAt holds the default value on creation for the created_at field.
	item.DefaultCreatedAt = itemDescCreatedAt.Default.(func() time.Time)
	// itemDescUpdatedAt is the schema descriptor for updated_at field.
	itemDescUpdatedAt := itemMixinFields0[1].Descriptor()
	// item.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	item.DefaultUpdatedAt = itemDescUpdatedAt.Default.(func() time.Time)
	// item.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	item.UpdateDefaultUpdatedAt = itemDescUpdatedAt.UpdateDefault.(func() time.Time)
	storagelocationMixin := schema.StorageLocation{}.Mixin()
	storagelocationMixinFields0 := storagelocationMixin[0].Fields()
	_ = storagelocationMixinFields0
	storagelocationFields := schema.StorageLocation{}.Fields()
	_ = storagelocationFields
	// storagelocationDescCreatedAt is the schema descriptor for created_at field.
	storagelocationDescCreatedAt := storagelocationMixinFields0[0].Descriptor()
	// storagelocation.DefaultCreatedAt holds the default value on creation for the created_at field.
	storagelocation.DefaultCreatedAt = storagelocationDescCreatedAt.Default.(func() time.Time)
	// storagelocationDescUpdatedAt is the schema descriptor for updated_at field.
	storagelocationDescUpdatedAt := storagelocationMixinFields0[1].Descriptor()
	// storagelocation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	storagelocation.DefaultUpdatedAt = storagelocationDescUpdatedAt.Default.(func() time.Time)
	// storagelocation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	storagelocation.UpdateDefaultUpdatedAt = storagelocationDescUpdatedAt.UpdateDefault.(func() time.Time)
}
