// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"goinv/ent/item"
	"goinv/ent/predicate"
	"goinv/ent/storagelocation"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StorageLocationQuery is the builder for querying StorageLocation entities.
type StorageLocationQuery struct {
	config
	ctx            *QueryContext
	order          []storagelocation.OrderOption
	inters         []Interceptor
	predicates     []predicate.StorageLocation
	withItems      *ItemQuery
	modifiers      []func(*sql.Selector)
	loadTotal      []func(context.Context, []*StorageLocation) error
	withNamedItems map[string]*ItemQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StorageLocationQuery builder.
func (slq *StorageLocationQuery) Where(ps ...predicate.StorageLocation) *StorageLocationQuery {
	slq.predicates = append(slq.predicates, ps...)
	return slq
}

// Limit the number of records to be returned by this query.
func (slq *StorageLocationQuery) Limit(limit int) *StorageLocationQuery {
	slq.ctx.Limit = &limit
	return slq
}

// Offset to start from.
func (slq *StorageLocationQuery) Offset(offset int) *StorageLocationQuery {
	slq.ctx.Offset = &offset
	return slq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (slq *StorageLocationQuery) Unique(unique bool) *StorageLocationQuery {
	slq.ctx.Unique = &unique
	return slq
}

// Order specifies how the records should be ordered.
func (slq *StorageLocationQuery) Order(o ...storagelocation.OrderOption) *StorageLocationQuery {
	slq.order = append(slq.order, o...)
	return slq
}

// QueryItems chains the current query on the "items" edge.
func (slq *StorageLocationQuery) QueryItems() *ItemQuery {
	query := (&ItemClient{config: slq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := slq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := slq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(storagelocation.Table, storagelocation.FieldID, selector),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, storagelocation.ItemsTable, storagelocation.ItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(slq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StorageLocation entity from the query.
// Returns a *NotFoundError when no StorageLocation was found.
func (slq *StorageLocationQuery) First(ctx context.Context) (*StorageLocation, error) {
	nodes, err := slq.Limit(1).All(setContextOp(ctx, slq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{storagelocation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (slq *StorageLocationQuery) FirstX(ctx context.Context) *StorageLocation {
	node, err := slq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StorageLocation ID from the query.
// Returns a *NotFoundError when no StorageLocation ID was found.
func (slq *StorageLocationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = slq.Limit(1).IDs(setContextOp(ctx, slq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{storagelocation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (slq *StorageLocationQuery) FirstIDX(ctx context.Context) int {
	id, err := slq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StorageLocation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StorageLocation entity is found.
// Returns a *NotFoundError when no StorageLocation entities are found.
func (slq *StorageLocationQuery) Only(ctx context.Context) (*StorageLocation, error) {
	nodes, err := slq.Limit(2).All(setContextOp(ctx, slq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{storagelocation.Label}
	default:
		return nil, &NotSingularError{storagelocation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (slq *StorageLocationQuery) OnlyX(ctx context.Context) *StorageLocation {
	node, err := slq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StorageLocation ID in the query.
// Returns a *NotSingularError when more than one StorageLocation ID is found.
// Returns a *NotFoundError when no entities are found.
func (slq *StorageLocationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = slq.Limit(2).IDs(setContextOp(ctx, slq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{storagelocation.Label}
	default:
		err = &NotSingularError{storagelocation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (slq *StorageLocationQuery) OnlyIDX(ctx context.Context) int {
	id, err := slq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StorageLocations.
func (slq *StorageLocationQuery) All(ctx context.Context) ([]*StorageLocation, error) {
	ctx = setContextOp(ctx, slq.ctx, "All")
	if err := slq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StorageLocation, *StorageLocationQuery]()
	return withInterceptors[[]*StorageLocation](ctx, slq, qr, slq.inters)
}

// AllX is like All, but panics if an error occurs.
func (slq *StorageLocationQuery) AllX(ctx context.Context) []*StorageLocation {
	nodes, err := slq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StorageLocation IDs.
func (slq *StorageLocationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if slq.ctx.Unique == nil && slq.path != nil {
		slq.Unique(true)
	}
	ctx = setContextOp(ctx, slq.ctx, "IDs")
	if err = slq.Select(storagelocation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (slq *StorageLocationQuery) IDsX(ctx context.Context) []int {
	ids, err := slq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (slq *StorageLocationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, slq.ctx, "Count")
	if err := slq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, slq, querierCount[*StorageLocationQuery](), slq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (slq *StorageLocationQuery) CountX(ctx context.Context) int {
	count, err := slq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (slq *StorageLocationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, slq.ctx, "Exist")
	switch _, err := slq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (slq *StorageLocationQuery) ExistX(ctx context.Context) bool {
	exist, err := slq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StorageLocationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (slq *StorageLocationQuery) Clone() *StorageLocationQuery {
	if slq == nil {
		return nil
	}
	return &StorageLocationQuery{
		config:     slq.config,
		ctx:        slq.ctx.Clone(),
		order:      append([]storagelocation.OrderOption{}, slq.order...),
		inters:     append([]Interceptor{}, slq.inters...),
		predicates: append([]predicate.StorageLocation{}, slq.predicates...),
		withItems:  slq.withItems.Clone(),
		// clone intermediate query.
		sql:  slq.sql.Clone(),
		path: slq.path,
	}
}

// WithItems tells the query-builder to eager-load the nodes that are connected to
// the "items" edge. The optional arguments are used to configure the query builder of the edge.
func (slq *StorageLocationQuery) WithItems(opts ...func(*ItemQuery)) *StorageLocationQuery {
	query := (&ItemClient{config: slq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	slq.withItems = query
	return slq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StorageLocation.Query().
//		GroupBy(storagelocation.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (slq *StorageLocationQuery) GroupBy(field string, fields ...string) *StorageLocationGroupBy {
	slq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StorageLocationGroupBy{build: slq}
	grbuild.flds = &slq.ctx.Fields
	grbuild.label = storagelocation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.StorageLocation.Query().
//		Select(storagelocation.FieldCreatedAt).
//		Scan(ctx, &v)
func (slq *StorageLocationQuery) Select(fields ...string) *StorageLocationSelect {
	slq.ctx.Fields = append(slq.ctx.Fields, fields...)
	sbuild := &StorageLocationSelect{StorageLocationQuery: slq}
	sbuild.label = storagelocation.Label
	sbuild.flds, sbuild.scan = &slq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StorageLocationSelect configured with the given aggregations.
func (slq *StorageLocationQuery) Aggregate(fns ...AggregateFunc) *StorageLocationSelect {
	return slq.Select().Aggregate(fns...)
}

func (slq *StorageLocationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range slq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, slq); err != nil {
				return err
			}
		}
	}
	for _, f := range slq.ctx.Fields {
		if !storagelocation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if slq.path != nil {
		prev, err := slq.path(ctx)
		if err != nil {
			return err
		}
		slq.sql = prev
	}
	return nil
}

func (slq *StorageLocationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StorageLocation, error) {
	var (
		nodes       = []*StorageLocation{}
		_spec       = slq.querySpec()
		loadedTypes = [1]bool{
			slq.withItems != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StorageLocation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StorageLocation{config: slq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(slq.modifiers) > 0 {
		_spec.Modifiers = slq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, slq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := slq.withItems; query != nil {
		if err := slq.loadItems(ctx, query, nodes,
			func(n *StorageLocation) { n.Edges.Items = []*Item{} },
			func(n *StorageLocation, e *Item) { n.Edges.Items = append(n.Edges.Items, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range slq.withNamedItems {
		if err := slq.loadItems(ctx, query, nodes,
			func(n *StorageLocation) { n.appendNamedItems(name) },
			func(n *StorageLocation, e *Item) { n.appendNamedItems(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range slq.loadTotal {
		if err := slq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (slq *StorageLocationQuery) loadItems(ctx context.Context, query *ItemQuery, nodes []*StorageLocation, init func(*StorageLocation), assign func(*StorageLocation, *Item)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*StorageLocation)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Item(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(storagelocation.ItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.item_storage_location
		if fk == nil {
			return fmt.Errorf(`foreign-key "item_storage_location" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "item_storage_location" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (slq *StorageLocationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := slq.querySpec()
	if len(slq.modifiers) > 0 {
		_spec.Modifiers = slq.modifiers
	}
	_spec.Node.Columns = slq.ctx.Fields
	if len(slq.ctx.Fields) > 0 {
		_spec.Unique = slq.ctx.Unique != nil && *slq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, slq.driver, _spec)
}

func (slq *StorageLocationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(storagelocation.Table, storagelocation.Columns, sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeInt))
	_spec.From = slq.sql
	if unique := slq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if slq.path != nil {
		_spec.Unique = true
	}
	if fields := slq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storagelocation.FieldID)
		for i := range fields {
			if fields[i] != storagelocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := slq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := slq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := slq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := slq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (slq *StorageLocationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(slq.driver.Dialect())
	t1 := builder.Table(storagelocation.Table)
	columns := slq.ctx.Fields
	if len(columns) == 0 {
		columns = storagelocation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if slq.sql != nil {
		selector = slq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if slq.ctx.Unique != nil && *slq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range slq.predicates {
		p(selector)
	}
	for _, p := range slq.order {
		p(selector)
	}
	if offset := slq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := slq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedItems tells the query-builder to eager-load the nodes that are connected to the "items"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (slq *StorageLocationQuery) WithNamedItems(name string, opts ...func(*ItemQuery)) *StorageLocationQuery {
	query := (&ItemClient{config: slq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if slq.withNamedItems == nil {
		slq.withNamedItems = make(map[string]*ItemQuery)
	}
	slq.withNamedItems[name] = query
	return slq
}

// StorageLocationGroupBy is the group-by builder for StorageLocation entities.
type StorageLocationGroupBy struct {
	selector
	build *StorageLocationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (slgb *StorageLocationGroupBy) Aggregate(fns ...AggregateFunc) *StorageLocationGroupBy {
	slgb.fns = append(slgb.fns, fns...)
	return slgb
}

// Scan applies the selector query and scans the result into the given value.
func (slgb *StorageLocationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, slgb.build.ctx, "GroupBy")
	if err := slgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StorageLocationQuery, *StorageLocationGroupBy](ctx, slgb.build, slgb, slgb.build.inters, v)
}

func (slgb *StorageLocationGroupBy) sqlScan(ctx context.Context, root *StorageLocationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(slgb.fns))
	for _, fn := range slgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*slgb.flds)+len(slgb.fns))
		for _, f := range *slgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*slgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := slgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StorageLocationSelect is the builder for selecting fields of StorageLocation entities.
type StorageLocationSelect struct {
	*StorageLocationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sls *StorageLocationSelect) Aggregate(fns ...AggregateFunc) *StorageLocationSelect {
	sls.fns = append(sls.fns, fns...)
	return sls
}

// Scan applies the selector query and scans the result into the given value.
func (sls *StorageLocationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sls.ctx, "Select")
	if err := sls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StorageLocationQuery, *StorageLocationSelect](ctx, sls.StorageLocationQuery, sls, sls.inters, v)
}

func (sls *StorageLocationSelect) sqlScan(ctx context.Context, root *StorageLocationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sls.fns))
	for _, fn := range sls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
