// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"goinv/ent/predicate"
	"goinv/ent/storagelocation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StorageLocationDelete is the builder for deleting a StorageLocation entity.
type StorageLocationDelete struct {
	config
	hooks    []Hook
	mutation *StorageLocationMutation
}

// Where appends a list predicates to the StorageLocationDelete builder.
func (sld *StorageLocationDelete) Where(ps ...predicate.StorageLocation) *StorageLocationDelete {
	sld.mutation.Where(ps...)
	return sld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sld *StorageLocationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sld.sqlExec, sld.mutation, sld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sld *StorageLocationDelete) ExecX(ctx context.Context) int {
	n, err := sld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sld *StorageLocationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(storagelocation.Table, sqlgraph.NewFieldSpec(storagelocation.FieldID, field.TypeInt))
	if ps := sld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sld.mutation.done = true
	return affected, err
}

// StorageLocationDeleteOne is the builder for deleting a single StorageLocation entity.
type StorageLocationDeleteOne struct {
	sld *StorageLocationDelete
}

// Where appends a list predicates to the StorageLocationDelete builder.
func (sldo *StorageLocationDeleteOne) Where(ps ...predicate.StorageLocation) *StorageLocationDeleteOne {
	sldo.sld.mutation.Where(ps...)
	return sldo
}

// Exec executes the deletion query.
func (sldo *StorageLocationDeleteOne) Exec(ctx context.Context) error {
	n, err := sldo.sld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storagelocation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sldo *StorageLocationDeleteOne) ExecX(ctx context.Context) {
	if err := sldo.Exec(ctx); err != nil {
		panic(err)
	}
}
