package goinv

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"goinv/ent"
)

// CreateItem is the resolver for the createItem field.
func (r *mutationResolver) CreateItem(ctx context.Context, input ent.CreateItemInput) (*ent.Item, error) {
	return r.client.Item.Create().SetInput(input).Save(ctx)
}

// CreateStorageLocation is the resolver for the createStorageLocation field.
func (r *mutationResolver) CreateStorageLocation(ctx context.Context, input ent.CreateStorageLocationInput) (*ent.StorageLocation, error) {
	return r.client.StorageLocation.Create().SetInput(input).Save(ctx)
}

// UpdateItem is the resolver for the updateItem field.
func (r *mutationResolver) UpdateItem(ctx context.Context, id int, input ent.UpdateItemInput) (*ent.Item, error) {
	return r.client.Item.UpdateOneID(id).SetInput(input).Save(ctx)
}

// UpdateStorageLocation is the resolver for the updateStorageLocation field.
func (r *mutationResolver) UpdateStorageLocation(ctx context.Context, id int, input ent.UpdateStorageLocationInput) (*ent.StorageLocation, error) {
	return r.client.StorageLocation.UpdateOneID(id).SetInput(input).Save(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
